### ISSUE TITLE
Doesn't return brackets on all keys

### ISSUE THREAD

**Issue by keithslater** [kcwiki/lua-json#2]
Hello, I'm trying out lua-json and running into an issue when converting json to lua. It seems to add brackets to some keys.

Here are some results I'm seeing-
```
DB = {
    _currentProfile = {
      ["test1"] = "Default",
      ["test2"] = "test123",
      ["test3"] = "Default",
      ["test4"] = "Default",
    },
```

When I would expect-

```
DB = {
   ["_currentProfile"] = {
      ["test1"] = "Default",
      ["test2"] = "test123",
      ["test3"] = "Default",
      ["test4"] = "Default",
    },
```

Any ideas?

**Comment by gakada** [comment]
In table fields `["a"] = b` is the [same](https://www.lua.org/manual/5.3/manual.html#9) as `a = b` when `a` is [`Name`](https://www.lua.org/manual/5.3/manual.html#3.1) ("any string of letters, digits, and underscores, not beginning with a digit [...]"), so the shorter/prettier variant is used when possible via

https://github.com/kcwiki/lua-json/blob/b162608dd02469e3ca6ee925cda68de86ed4adc9/index.js#L6

**Comment by gakada** [comment]
Though then it should be `test1`/etc. instead of `["test1"]`/etc. as well, so that one is not intended. I will take a look later.

**Comment by gakada** [comment]
Can't reproduce here:
```js
// test.js
const { format } = require('lua-json')

console.log(
  format({
    DB: {
      _currentProfile: {
        test1: 'Default',
        test2: 'test123',
        test3: 'Default',
        test4: 'Default',
      },
    },
  }),
)
```
```lua
-- node test
return {
  DB = {
    _currentProfile = {
      test1 = 'Default',
      test2 = 'test123',
      test3 = 'Default',
      test4 = 'Default',
    },
  },
}
```
Current [test](https://github.com/kcwiki/lua-json/blob/master/test.js) also covers this (all keys are short except those that can't be).

**Comment by keithslater** [comment]
Sounds like it's working how you intended. I'll close this and possibly fork as I have an odd use case.

**Comment by gakada** [comment]
I plan to add some more options for pretty printing, something like an option to always use brackets can be an option as well.
